version: '3.3'

services:
    api:
        build: ./docker/api
        ports:
          - "8581:8000"
        networks:
          - frontend
          - backend
        links:
          - mongodb
        restart: always

    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - db-data:/data/db
        expose:
            - "27017"
        ports:
            - "27017:27017"
        networks:
            - backend
        restart: always

    web:
        image: nginx:alpine
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/front.conf:/etc/nginx/conf.d/default.conf
          - ./front:/home/front
        ports:
            - "8580:80"
        networks:
          - frontend
          - backend
        links:
          - api
        restart: always

networks:
  frontend:
  backend:

volumes:
  db-data:
